# Generated by Django 4.0.3 on 2022-05-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('fromto', models.CharField(max_length=89)),
                ('destination', models.CharField(max_length=89)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.EmailField(default=None, max_length=90)),
            ],
        ),
    ]
