# Generated by Django 4.0.3 on 2022-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='userid',
            field=models.CharField(default=None, max_length=90),
        ),
    ]
